# This file contains all available configuration options
# with their default values.

# Options for analysis running
run:
  tests: true
  timeout: 5m

# Output configuration options
output:
  formats:
    - format: line-number

# All available settings of specific linters
linters-settings:
  misspell:
    locale: US
    ignore-words:
      - noteable
  revive:
    enable-all-rules: false
    rules:
      - name: deep-exit

linters:
  enable:
    - asciicheck
    - dogsled
    - errorlint
    - exportloopref
    - goconst
    - gosimple
    - govet
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable:
    - errcheck
  disable-all: false
  fast: false

issues:
  # List of regexps of issue texts to exclude.
  exclude:
    - "^.*, make it a constant$"

  # Maximum issues count per one linter (set to 0 to disable)
  max-issues-per-linter: 0

  # Maximum count of issues with the same text (set to 0 to disable)
  max-same-issues: 0