name: Lint and Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint_and_test:
    name: Lint and Test - 1.23.x
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint package
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Test package
        run: |
          go test -v ./test -coverprofile=coverage.txt -covermode count
          go tool cover -func coverage.txt
        env:
          EVE_USER: ${{ secrets.EVE_USER }}
          EVE_PASSWORD: ${{ secrets.EVE_PASSWORD }}
          EVE_HOST: ${{ secrets.EVE_HOST }}
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          report: 'true'
          amend: 'true'
          reuse-go: 'true'
        if:
          github.event_name == 'push'
        continue-on-error: true